language: java
jdk: oraclejdk8
script:
  - ./gradlew check
  - uname -a
after_script:
  - java -cp ./build/classes/java/main/  com.hello.echo.server.RealNioEchoServer &
  - python ./tests/python/test-echo-server.py
#after_success: - bash <(curl -s https://codecov.io/bash
