matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - ./gradlew check
        - python --version
        - uname -a
      #after_success: - bash <(curl -s https://codecov.io/bash
    - language: python
      python: 2.7
      script:
        - java -cp ./build/classes/java/main/  com.hello.echo.server.RealNioEchoServer &
        - ps -elf |grep RealNioEchoServer
        - netstat -tuanp |grep java
        - python ./tests/python/test-echo-server.py

